apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "actions-runner-controller-2.managerCrdClusterRoleName" . }}
rules:
- apiGroups:
  - actions.github.com
  resources:
  - autoscalingrunnersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - autoscalingrunnersets/finalizers
  verbs:
  - update
- apiGroups:
  - actions.github.com
  resources:
  - autoscalingrunnersets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - autoscalinglisteners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - autoscalinglisteners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - autoscalinglisteners/finalizers
  verbs:
  - update
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunnersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunnersets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners/status
  verbs:
  - get
  - patch
  - update