apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "actions-runner-controller-2.managerRoleBinding" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "actions-runner-controller-2.managerRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "actions-runner-controller-2.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}